CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "role" varchar NOT NULL,
  "organization_name" varchar,
  "created_at" timestamp
);

CREATE TABLE "employees" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "first_name" varchar,
  "last_name" varchar,
  "cnp" varchar UNIQUE NOT NULL,
  "username" varchar,
  "password" varchar,
  "email" varchar,
  "address" varchar,
  "city" varchar,
  "country" varchar
);

CREATE TABLE "salaries" (
  "salary_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "base_salary" decimal,
  "month" date
);

CREATE TABLE "bonuses" (
  "bonus_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "amount" decimal,
  "description" varchar,
  "month" date
);

CREATE TABLE "vacations" (
  "vacation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "start_date" date,
  "end_date" date,
  "number_of_days" int,
  "reason" varchar
);

CREATE TABLE "work_days" (
  "work_day_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "month" date,
  "number_of_days" int
);

CREATE TABLE "archived_files" (
  "file_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "file_name" varchar,
  "file_type" varchar,
  "path" varchar,
  "sent_date" date
);

COMMENT ON COLUMN "users"."organization_name" IS 'VARCHAR2(15)';

ALTER TABLE "employees" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "salaries" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "bonuses" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "vacations" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "work_days" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "archived_files" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");
