CREATE TABLE "employees" (
  "employee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manager_id" int,
  "role" varchar NOT NULL,
  "first_name" varchar,
  "last_name" varchar,
  "cnp" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "address" varchar,
  "city" varchar,
  "country" varchar,
  "created_at" timestamp
);

CREATE TABLE "salaries" (
  "salary_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "base_salary" decimal,
  "month" date
);

CREATE TABLE "bonuses" (
  "bonus_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "amount" decimal,
  "description" varchar,
  "month" date
);

CREATE TABLE "vacations" (
  "vacation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "start_date" date,
  "end_date" date,
  "number_of_days" int,
  "reason" varchar
);

CREATE TABLE "work_days" (
  "work_day_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "month" date,
  "number_of_days" int
);

CREATE TABLE "archived_files" (
  "file_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "employee_id" int,
  "file_name" varchar,
  "file_type" varchar,
  "path" varchar,
  "sent_date" date
);

COMMENT ON COLUMN "employees"."role" IS '''manager'' sau ''employee''';

ALTER TABLE "employees" ADD FOREIGN KEY ("manager_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "salaries" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "bonuses" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "vacations" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "work_days" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");

ALTER TABLE "archived_files" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("employee_id");
